(setq pdf-info-epdfinfo-program "~/.emacs.d/site-lisp/win_software/epdfinfo/epdfinfo.exe")
(require 'pdf-tools)
(require 'pdf-loader)
(require 'pdf-occur)
(require 'pdf-annot)
(require 'pdf-outline)
(require 'pdf-cache)
(require 'pdf-dev)
(require 'pdf-history)
(require 'pdf-info)
(require 'pdf-isearch)
(require 'pdf-links)
(require 'pdf-macs)
(require 'pdf-misc)
(require 'pdf-sync)
(require 'pdf-util)
(require 'pdf-view)
(require 'pdf-virtual)
(pdf-loader-install)
(add-hook 'pdf-view-mode-hook (lambda () (display-line-numbers-mode -1)))

(defun pdf-view-kill-rmn-ring-save ()
  "Copy the region to the `kill-ring' after remove all newline characters."
  (interactive)
  (pdf-view-assert-active-region)
  (let* ((txt (replace-regexp-in-string "\n" " "
        (car (pdf-view-active-region-text)))))
    (pdf-view-deactivate-region)
	(kill-new txt)))
(pdf-view-set-selection-style "glyph")

(defun noter-open ()
  (interactive)
  (progn
    (require 'init-org)
    (org-noter))
  )

(major-mode-hydra-define pdf-view-mode
 (:title (pretty-hydra-title "Pdf Commands" 'faicon "nf-fa-file_pdf_o") :color amaranth :quit-key ("q" "C-g"))
 ("Edit"
  (("a" pdf-annot-add-markup-annotation "annotate" :exit t)
   ("t" pdf-annot-add-text-annotation "text" :exit t)
   ("d" pdf-annot-delete "delete" :exit t)
   ("l" pdf-annot-list-annotations "list" :exit t))
  "View"
  (("G" pdf-view-goto-page "go to page" :exit t)
   ("g" pdf-view-goto-label "go to label" :exit t)
   ("s" pdf-view-set-selection-style "set selection style" :exit t)
   ("y" pdf-view-kill-rmn-ring-save "copy text" :exit t)
   )
  "Notes"
  (("N" noter-open "noter" :exit t)
   ("i" org-noter-insert-note "insert note" :exit t)
   ("I" org-noter-insert-precise-note "insert precise note" :exit t)
   ("c" org-noter-sync-current-note "sync current" :exit t)
   ("p" org-noter-sync-prev-note "sync pre" :exit t)
   ("n" org-noter-sync-next-note "sync next" :exit t)
   )
  "Occur"
  (("o" pdf-occur "occur" :exit t)
   ("O" pdf-occur-next-error "next occur")
   )
 ))

(provide 'init-pdf)
